// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"subkegiatanServices/app"
	"subkegiatanServices/controller"
	"subkegiatanServices/repository"
	"subkegiatanServices/service"
)

import (
	_ "subkegiatanServices/docs"
)

// Injectors from injector.go:

func InitializedServer() *echo.Echo {
	subkegiatanRepositoryImpl := repository.NewSubkegiatanRepositoryImpl()
	db := app.GetConnection()
	v := _wireValue
	validate := validator.New(v...)
	subkegiatanServiceImpl := service.NewSubkegiatanServiceImpl(subkegiatanRepositoryImpl, db, validate)
	subkegiatanControllerImpl := controller.NewSubkegiatanControllerImpl(subkegiatanServiceImpl)
	echoEcho := app.NewRouter(subkegiatanControllerImpl)
	return echoEcho
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var subkegiatanSet = wire.NewSet(repository.NewSubkegiatanRepositoryImpl, wire.Bind(new(repository.SubkegiatanRepository), new(*repository.SubkegiatanRepositoryImpl)), service.NewSubkegiatanServiceImpl, wire.Bind(new(service.SubkegiatanService), new(*service.SubkegiatanServiceImpl)), controller.NewSubkegiatanControllerImpl, wire.Bind(new(controller.SubkegiatanController), new(*controller.SubkegiatanControllerImpl)))
